import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import { Providers } from '@/redux/provider'
import Header from '@/components/Common/Header'
import '../global.css';

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Circle Cafe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
        {/* <script async defer crossOrigin="anonymous" src="https://connect.facebook.net/zh_TW/sdk.js" nonce="Zvy4JATi"></script> */}
      </head>
      <body>
        <Providers>
          <nav className='header'>
            <Header/>
          </nav>
          {children}
        </Providers>
      </body>
    </html>
  )
}
